global:
  scrape_interval: 15s  # 기본 스크레이프 간격

scrape_configs:
  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']  # Promtail의 메트릭을 수집

  - job_name: 'spring-boot'
    scrape_interval: 15s
    http_sd_configs:
      - url: http://172.31.10.0:8000/actuator/prometheus
