version: '3.7'

services:
  promtail:
    image: grafana/promtail:latest
    ports:
      - "9080:9080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
      - /var/log/game:/var/log/game
      - /var/log/apigateway:/var/log/apigateway
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - monitoring

networks:
  monitoring:
    external: true
