server:
  http_listen_port: 9080
  log_level: info

positions:
  filename: /var/positions.yaml

clients:
  - url: http://172.31.2.126:3100/loki/api/v1/push

scrape_configs:
  - job_name: user-server-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/user/*.log